# permissions for end users to view peerpodconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peerpodconfig-viewer-role
rules:
- apiGroups:
  - peerpod.confidentialcontainers.io.my.domain
  resources:
  - peerpodconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - peerpod.confidentialcontainers.io.my.domain
  resources:
  - peerpodconfigs/status
  verbs:
  - get
